server:
  port: 8082

spring:
  application:
    name: temperature-monitoring
  datasource:
    url: jdbc:h2:file:./algasensors-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
